//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT.Data.UnitTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public short Age { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<int> IQ { get; set; }
        public System.DateTime Birthday { get; set; }
        public Nullable<long> FavoriteNumber { get; set; }
        public bool IsMarried { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
    }
}
